export const Routes = {
  Auth: 'Auth',
  Login: 'Login',
  Register: 'Register',
  Home: 'Home',
  Dashboard: 'Dashboard',
  Lessons: 'Lessons',
  Explore: 'Explore',
  Profile: 'Profile',
  Language: 'Language',
  Lesson: 'Lesson',
  ProfileInfos: 'ProfileInfos',
  PaymentMethods: 'PaymentMethods',
  PaymentHistory: 'PaymentHistory',
  NewCard: 'NewCard',
  Teacher: 'Teacher',
  Colab:'Colab',
  Forgot: 'Forgot',
  Chat: 'Chat',
  Room: 'Room',
  NewAddress: 'NewAddress'
}
